# Site settings
title: "Step Up to IT"
email: jbeaudin@vtworksforwomen.org
description: > # this means to ignore newlines until "baseurl:"
    Step Up to Information Technology is a newly designed, nine-week 
    program for women interested in the field of IT, focusing on front-end 
    web development skills such as coding and programming. 
baseurl: "/step-up-it" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
exclude: ["README.md", "NOTES.md"]
twitter_username: VTWorks4Women
github_username:  VTWorksForWomen


vww_url: "http://www.vtworksforwomen.org"
contact_name: Jenny Beaudin
contact_title: Step Up Program Coordinator
contact_email: jbeaudin@vtworksforwomen.org
contact_phone: 802.622.0400, ext. 150

# Build settings
markdown: kramdown
kramdown:
  parse_block_html: true
